import logging
StandardLogger = logging.getLogger("Standard")
StandardLogger.setLevel(logging.WARNING)
sHandler = logging.StreamHandler()
format = logging.Formatter('%(name)s %(asctime)s {%(levelname)s}:%(message)s', datefmt='%Y-%m-%d %H:%M:%S')
sHandler.setFormatter(format)
StandardLogger.addHandler(sHandler)

OpsCommandLogger = logging.getLogger("OpsCommand")
OpsCommandLogger.setLevel(logging.INFO)
fHandler = logging.FileHandler('.\OpsCommand.opsc', mode='w')
format = logging.Formatter('%(message)s')
fHandler.setFormatter(format)
OpsCommandLogger.addHandler(fHandler)
OpsCommandLogger.info("import openseespy.opensees as ops")